# Generated by Django 3.2.7 on 2021-10-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stopapp', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='basket',
            new_name='basket_no',
        ),
    ]
